[package]
name = "onepack_lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postcard = "1.0.6"
serde = { version = "1.0.185", features = ["derive"] }
